# -*- coding: utf-8 -*-
"""Sentiment analysis of Reviews.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-7b5KB0OdeHEc_06KIXzJ1XZRBpHvbpd
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb

!pip install textblob
from textblob import TextBlob
import warnings
warnings.filterwarnings('ignore')

df=pd.read_csv('reviews.csv')
df.head()

df.info()

df.shape

df.ndim

df.size

df.keys()

df.describe()

df.dtypes

df.isnull()

df.isnull().sum()

samp=df.sample(10000)

samp.shape

pol=[]
for i in samp.Review.values:
  try:
    analysis=TextBlob(i)
    pol.append(analysis.sentiment.polarity)
  except:
    pol.append(0)

samp['pol']=pol

samp['pol'][samp.pol==0]=0
samp['pol'][samp.pol>0]=1
samp['pol'][samp.pol<0]=-1

df_positive=samp[samp.pol==1]
df_positive.head()

df_negative=samp[samp.pol== -1]
df_negative.head()

df_neutral=samp[samp.pol==0]
df_neutral.head()

samp.pol.value_counts().plot.bar(color=['green', 'grey', 'red'])
plt.title('Distribution of Sentiments in Spotify Reviews')
plt.xlabel('Sentiment Category')
plt.ylabel('Number of Reviews')
plt.xticks(ticks=[0,1,2], labels=['Positive', 'Neutral', 'Negative'], rotation=0)
plt.show()

pol=[]
subj=[]
for i in samp.Review.values:
  try:
    analysis=TextBlob(i)
    pol.append(analysis.sentiment.polarity)
    subj.append(analysis.sentiment.subjectivity)
  except:
    pol.append(0)
    subj.append(0)
samp['pol']=pol
samp['subj']=subj

sb.scatterplot(data=samp,x='pol',y='subj')
plt.xlabel('Polarity')
plt.ylabel('Subjectivity')
plt.title('Sentiment Analysis')
plt.show()

from wordcloud import WordCloud
df['Review']=df['Review'].astype(str)
all_comments=''.join(df['Review'].values)
wordcloud=WordCloud(width=800,height=400,background_color='black').generate(all_comments)
plt.figure(figsize=(15,10))
plt.imshow(wordcloud,interpolation='bilinear')
plt.axis('off')
plt.title('Word cloud of Reviews')
plt.show()